"""empty message

Revision ID: 42c071639815
Revises: 
Create Date: 2020-07-01 07:30:02.258652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42c071639815'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('passworld', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('content', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('user_comment', table_name='news_comment_liking')
    op.drop_table('news_comment_liking')
    op.drop_index('account', table_name='mis_administrator')
    op.drop_table('mis_administrator')
    op.drop_table('user_legalize_log')
    op.drop_index('year_month_day_hour_type', table_name='statistics_basic')
    op.drop_table('statistics_basic')
    op.drop_table('recommend_sensitive_word')
    op.drop_table('statistics_read_source_total')
    op.drop_table('news_article_statistic')
    op.drop_index('name', table_name='mis_administrator_group')
    op.drop_table('mis_administrator_group')
    op.drop_table('news_comment')
    op.drop_index('user_article', table_name='news_report')
    op.drop_table('news_report')
    op.drop_table('user_search')
    op.drop_table('statistics_search_total')
    op.drop_index('article_status', table_name='news_article_basic')
    op.drop_table('news_article_basic')
    op.drop_table('user_qualification')
    op.drop_table('global_announcement')
    op.drop_table('sys_college')
    op.drop_table('sys_university')
    op.drop_table('user_auths')
    op.drop_table('mis_operation_log')
    op.drop_table('statistics_sales_total')
    op.drop_index('name', table_name='mis_permission')
    op.drop_table('mis_permission')
    op.drop_index('channel_name', table_name='news_channel')
    op.drop_table('news_channel')
    op.drop_table('mis_group_permission')
    op.drop_index('user_material', table_name='user_material')
    op.drop_table('user_material')
    op.drop_index('user_article', table_name='news_collection')
    op.drop_table('news_collection')
    op.drop_table('sys_district')
    op.drop_table('news_article_content')
    op.drop_index('year_month_day_hour_keyword', table_name='statistics_search')
    op.drop_table('statistics_search')
    op.drop_index('mobile', table_name='user_basic')
    op.drop_table('user_basic')
    op.drop_index('user_channel', table_name='news_user_channel')
    op.drop_table('news_user_channel')
    op.drop_index('user_target', table_name='user_relation')
    op.drop_table('user_relation')
    op.drop_index('user_article', table_name='news_attitude')
    op.drop_table('news_attitude')
    op.drop_table('user_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('gender', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='性别，0-男，1-女'),
    sa.Column('birthday', sa.DATE(), nullable=True, comment='生日'),
    sa.Column('real_name', mysql.VARCHAR(length=32), nullable=True, comment='真实姓名'),
    sa.Column('id_number', mysql.VARCHAR(length=20), nullable=True, comment='身份证号'),
    sa.Column('id_card_front', mysql.VARCHAR(length=128), nullable=True, comment='身份证正面'),
    sa.Column('id_card_back', mysql.VARCHAR(length=128), nullable=True, comment='身份证背面'),
    sa.Column('id_card_handheld', mysql.VARCHAR(length=128), nullable=True, comment='手持身份证'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('register_media_time', mysql.DATETIME(), nullable=True, comment='注册自媒体时间'),
    sa.Column('area', mysql.VARCHAR(length=20), nullable=True, comment='地区'),
    sa.Column('company', mysql.VARCHAR(length=20), nullable=True, comment='公司'),
    sa.Column('career', mysql.VARCHAR(length=20), nullable=True, comment='职业'),
    sa.PrimaryKeyConstraint('user_id'),
    comment='用户资料表',
    mysql_comment='用户资料表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('news_attitude',
    sa.Column('attitude_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('article_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='文章ID'),
    sa.Column('attitude', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='态度，0-不喜欢，1-喜欢'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('attitude_id'),
    comment='用户文章态度表',
    mysql_comment='用户文章态度表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_article', 'news_attitude', ['user_id', 'article_id'], unique=True)
    op.create_table('user_relation',
    sa.Column('relation_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('target_user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='目标用户ID'),
    sa.Column('relation', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='关系，0-取消，1-关注，2-拉黑'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('relation_id'),
    comment='用户关系表',
    mysql_comment='用户关系表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_target', 'user_relation', ['user_id', 'target_user_id'], unique=True)
    op.create_table('news_user_channel',
    sa.Column('user_channel_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('channel_id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False, comment='频道ID'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否删除, 0-未删除, 1-已删除'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('sequence', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='序号'),
    sa.PrimaryKeyConstraint('user_channel_id'),
    comment='用户关注频道表',
    mysql_comment='用户关注频道表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_channel', 'news_user_channel', ['user_id', 'channel_id'], unique=True)
    op.create_table('user_basic',
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True, zerofill=True), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('account', mysql.VARCHAR(length=20), nullable=True, comment='账号'),
    sa.Column('email', mysql.VARCHAR(length=20), nullable=True, comment='邮箱'),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='状态，是否可用，0-不可用，1-可用'),
    sa.Column('mobile', mysql.CHAR(length=11), nullable=True, comment='手机号'),
    sa.Column('password', mysql.VARCHAR(length=93), nullable=True, comment='密码'),
    sa.Column('username', mysql.VARCHAR(length=32), nullable=True, comment='昵称'),
    sa.Column('profile_photo', mysql.VARCHAR(length=128), nullable=True, comment='头像'),
    sa.Column('last_login', mysql.DATETIME(), nullable=True, comment='最后登录时间'),
    sa.Column('is_media', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='是否是自媒体，0-不是，1-是'),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='是否实名认证，0-不是，1-是'),
    sa.Column('introduction', mysql.VARCHAR(length=50), nullable=True, comment='简介'),
    sa.Column('certificate', mysql.VARCHAR(length=30), nullable=True, comment='认证'),
    sa.Column('article_count', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='发文章数'),
    sa.Column('following_count', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='关注的人数'),
    sa.Column('fans_count', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='被关注的人数'),
    sa.Column('like_count', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='累计点赞人数'),
    sa.Column('read_count', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='累计阅读人数'),
    sa.Column('gmt_created', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('gmt_modified', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('faculty', mysql.VARCHAR(length=255), nullable=True, comment='学院'),
    sa.Column('faculty_id', mysql.BIGINT(display_width=255), autoincrement=False, nullable=True, comment='学校id'),
    sa.Column('university', mysql.VARCHAR(length=255), nullable=True, comment='学校'),
    sa.Column('university_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='学校id'),
    sa.Column('sex', mysql.TINYINT(display_width=3), autoincrement=False, nullable=True, comment='性别'),
    sa.PrimaryKeyConstraint('user_id'),
    comment='用户基本信息表',
    mysql_comment='用户基本信息表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('mobile', 'user_basic', ['mobile'], unique=True)
    op.create_table('statistics_search',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('year', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='年'),
    sa.Column('month', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='月'),
    sa.Column('day', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='天'),
    sa.Column('hour', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='时'),
    sa.Column('keyword', mysql.VARCHAR(length=100), nullable=False, comment='搜索关键字'),
    sa.Column('user_count', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='搜索用户数'),
    sa.Column('count', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='搜索次数'),
    sa.Column('date_time', mysql.DATETIME(), nullable=False, comment='跟年月日时匹配的时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='搜索统计',
    mysql_comment='搜索统计',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('year_month_day_hour_keyword', 'statistics_search', ['year', 'month', 'day', 'hour', 'keyword'], unique=True)
    op.create_table('news_article_content',
    sa.Column('article_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='文章ID'),
    sa.Column('content', mysql.LONGTEXT(), nullable=False, comment='文章内容'),
    sa.PrimaryKeyConstraint('article_id'),
    comment='文章内容表',
    mysql_comment='文章内容表',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('sys_district',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('gmt_created', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('gmt_modified', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('show_seq', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('parent_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('district_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('grade', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('grade_cn', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('district_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('district_status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hot_city', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pinyin', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pinyin_first', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('news_collection',
    sa.Column('collection_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('article_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='文章ID'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否取消收藏, 0-未取消, 1-已取消'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('collection_id'),
    comment='用户收藏表',
    mysql_comment='用户收藏表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_article', 'news_collection', ['user_id', 'article_id'], unique=True)
    op.create_table('user_material',
    sa.Column('material_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='素材id'),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('type', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='素材类型，0-图片, 1-视频, 2-音频'),
    sa.Column('hash', mysql.VARCHAR(length=128), nullable=True, comment='素材指纹'),
    sa.Column('url', mysql.VARCHAR(length=128), nullable=False, comment='素材链接地址'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='状态，0-待审核，1-审核通过，2-审核失败，3-已删除'),
    sa.Column('reviewer_id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True, comment='审核人员ID'),
    sa.Column('review_time', mysql.DATETIME(), nullable=True, comment='审核时间'),
    sa.Column('is_collected', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否收藏，0-未收藏，1-已收藏'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('material_id'),
    comment='用户素材表',
    mysql_comment='用户素材表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_material', 'user_material', ['user_id', 'hash'], unique=True)
    op.create_table('mis_group_permission',
    sa.Column('group_permission_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='组权限ID'),
    sa.Column('group_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='角色/组ID'),
    sa.Column('permission_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='权限ID'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('group_permission_id'),
    comment='组权限表',
    mysql_comment='组权限表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('news_channel',
    sa.Column('channel_id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False, comment='频道ID'),
    sa.Column('channel_name', mysql.VARCHAR(length=32), nullable=False, comment='频道名称'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('sequence', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='序号'),
    sa.Column('is_visible', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否可见'),
    sa.Column('is_default', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否默认'),
    sa.PrimaryKeyConstraint('channel_id'),
    comment='新闻频道表',
    mysql_comment='新闻频道表',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_index('channel_name', 'news_channel', ['channel_name'], unique=True)
    op.create_table('mis_permission',
    sa.Column('permission_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='权限ID'),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False, comment='权限'),
    sa.Column('type', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='权限类型'),
    sa.Column('parent_id', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='父权限的ID'),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=True, comment='权限点代码'),
    sa.Column('sequence', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='序列'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('permission_id'),
    comment='权限表',
    mysql_comment='权限表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'mis_permission', ['name'], unique=True)
    op.create_table('statistics_sales_total',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('area', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='地区'),
    sa.Column('money', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='金额(单位:分)'),
    sa.PrimaryKeyConstraint('id'),
    comment='销售额统计-总数',
    mysql_comment='销售额统计-总数',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mis_operation_log',
    sa.Column('operation_log_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='日志ID'),
    sa.Column('administrator_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='管理员ID'),
    sa.Column('ip', mysql.VARCHAR(length=16), nullable=False, comment='ip地址'),
    sa.Column('operation', mysql.VARCHAR(length=50), nullable=True, comment='操作'),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=False, comment='描述'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('operation_log_id'),
    comment='运营日志',
    mysql_comment='运营日志',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_auths',
    sa.Column('auth_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('identity_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('identifier', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('credential', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('auth_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_university',
    sa.Column('id', mysql.BIGINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('university', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('gmt_created', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('gmt_modified', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_college',
    sa.Column('college_id', mysql.BIGINT(display_width=11), autoincrement=True, nullable=False),
    sa.Column('college', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('university_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('gmt_created', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('gmt_modified', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('college_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('global_announcement',
    sa.Column('announcement_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='公告id'),
    sa.Column('title', mysql.VARCHAR(length=32), nullable=False, comment='标题'),
    sa.Column('content', mysql.TEXT(), nullable=False, comment='正文'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='状态，0-待发布，1-已发布，2-已撤下'),
    sa.Column('publish_time', mysql.DATETIME(), nullable=True, comment='发布时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('announcement_id'),
    comment='系统公告表',
    mysql_comment='系统公告表',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('user_qualification',
    sa.Column('qualification_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='资质认证材料ID'),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False, comment='姓名'),
    sa.Column('id_number', mysql.VARCHAR(length=20), nullable=True, comment='身份证号'),
    sa.Column('industry', mysql.VARCHAR(length=200), nullable=False, comment='行业'),
    sa.Column('company', mysql.VARCHAR(length=200), nullable=False, comment='公司'),
    sa.Column('position', mysql.VARCHAR(length=200), nullable=False, comment='职位'),
    sa.Column('add_info', mysql.VARCHAR(length=200), nullable=True, comment='补充信息'),
    sa.Column('id_card_front', mysql.VARCHAR(length=200), nullable=True, comment='身份证正面'),
    sa.Column('id_card_back', mysql.VARCHAR(length=200), nullable=True, comment='身份证背面'),
    sa.Column('id_card_handheld', mysql.VARCHAR(length=200), nullable=True, comment='手持身份证'),
    sa.Column('qualification_img', mysql.VARCHAR(length=200), nullable=True, comment='证明资料'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('qualification_id'),
    comment='用户资质认证材料',
    mysql_comment='用户资质认证材料',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('news_article_basic',
    sa.Column('article_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='文章ID'),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('channel_id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False, comment='频道ID'),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=False, comment='标题'),
    sa.Column('cover', mysql.JSON(), nullable=False, comment='封面'),
    sa.Column('is_advertising', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否投放广告，0-不投放，1-投放'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='贴文状态，0-草稿，1-待审核，2-审核通过，3-审核失败，4-已删除'),
    sa.Column('reviewer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='审核人员ID'),
    sa.Column('review_time', mysql.DATETIME(), nullable=True, comment='审核时间'),
    sa.Column('delete_time', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('reject_reason', mysql.VARCHAR(length=200), nullable=True, comment='驳回原因'),
    sa.Column('comment_count', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='累计评论数'),
    sa.Column('allow_comment', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='是否允许评论，0-不允许，1-允许'),
    sa.PrimaryKeyConstraint('article_id'),
    comment='文章基本信息表',
    mysql_comment='文章基本信息表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('article_status', 'news_article_basic', ['status'], unique=False)
    op.create_table('statistics_search_total',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('keyword', mysql.VARCHAR(length=100), nullable=False, comment='搜索关键字'),
    sa.Column('user_count', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='搜索用户数'),
    sa.Column('count', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='搜索次数'),
    sa.PrimaryKeyConstraint('id'),
    comment='搜索统计-总数',
    mysql_comment='搜索统计-总数',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_search',
    sa.Column('search_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('keyword', mysql.VARCHAR(length=100), nullable=False, comment='关键词'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否删除, 0-未删除，1-已删除'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('search_id'),
    comment='用户搜索历史',
    mysql_comment='用户搜索历史',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('news_report',
    sa.Column('report_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('article_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='文章ID'),
    sa.Column('type', mysql.TINYINT(display_width=2), autoincrement=False, nullable=True, comment='类型，0-其他问题，1-标题夸张，2-低俗色情，3-错别字多，4-旧闻重复，5-广告软文，6-内容不实，7-涉嫌违法犯罪，8-侵权'),
    sa.Column('remark', mysql.VARCHAR(length=200), nullable=True, comment='备注问题'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('report_id'),
    comment='文章举报',
    mysql_comment='文章举报',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_article', 'news_report', ['user_id', 'article_id'], unique=True)
    op.create_table('news_comment',
    sa.Column('comment_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='评论id'),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('article_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='文章ID'),
    sa.Column('parent_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=True, comment='评论ID'),
    sa.Column('like_count', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='点赞数'),
    sa.Column('reply_count', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='回复数'),
    sa.Column('content', mysql.VARCHAR(length=200), nullable=False, comment='评论内容'),
    sa.Column('is_top', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否置顶'),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='状态，0-待审核，1-审核通过，2-审核失败，3-已删除'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('comment_id'),
    comment='文章评论',
    mysql_comment='文章评论',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('mis_administrator_group',
    sa.Column('group_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='管理员角色/组ID'),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False, comment='角色/组'),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='状态'),
    sa.Column('remark', mysql.VARCHAR(length=100), nullable=True, comment='备注'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('group_id'),
    comment='管理员角色/组',
    mysql_comment='管理员角色/组',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'mis_administrator_group', ['name'], unique=True)
    op.create_table('news_article_statistic',
    sa.Column('article_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='文章ID'),
    sa.Column('read_count', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='阅读量'),
    sa.Column('like_count', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='点赞数'),
    sa.Column('dislike_count', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='不喜欢数'),
    sa.Column('repost_count', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='转发数'),
    sa.Column('collect_count', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='收藏数'),
    sa.Column('fans_comment_count', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='粉丝评论数'),
    sa.PrimaryKeyConstraint('article_id'),
    comment='文章统计表',
    mysql_comment='文章统计表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('statistics_read_source_total',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('source', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='阅读来源'),
    sa.Column('count', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='阅读数量'),
    sa.Column('count_20_down', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='完成度在20%以下的数量'),
    sa.Column('count_20_80', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='完成度在20%-80%的数量'),
    sa.Column('count_80_up', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='完成度在80%以上的数量'),
    sa.PrimaryKeyConstraint('id'),
    comment='阅读来源统计-总数',
    mysql_comment='阅读来源统计-总数',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recommend_sensitive_word',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='敏感词ID'),
    sa.Column('word', mysql.VARCHAR(length=50), nullable=False, comment='敏感词'),
    sa.Column('weights', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='权重'),
    sa.Column('hold_count', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='拦截次数'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='敏感词',
    mysql_comment='敏感词',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('statistics_basic',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('year', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='年'),
    sa.Column('month', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='月'),
    sa.Column('day', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='天'),
    sa.Column('hour', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='时'),
    sa.Column('type', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='统计类型'),
    sa.Column('count', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='数量'),
    sa.Column('date_time', mysql.DATETIME(), nullable=False, comment='跟年月日时匹配的时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='基本统计',
    mysql_comment='基本统计',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('year_month_day_hour_type', 'statistics_basic', ['year', 'month', 'day', 'hour', 'type'], unique=True)
    op.create_table('user_legalize_log',
    sa.Column('legalize_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='认证申请ID'),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('type', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='认证类型'),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='申请状态'),
    sa.Column('reject_reason', mysql.VARCHAR(length=200), nullable=True, comment='驳回原因'),
    sa.Column('qualification_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='资质认证材料ID'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('legalize_id'),
    comment='用户认证申请记录',
    mysql_comment='用户认证申请记录',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mis_administrator',
    sa.Column('administrator_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='管理员ID'),
    sa.Column('account', mysql.VARCHAR(length=20), nullable=False, comment='用户ID'),
    sa.Column('password', mysql.VARCHAR(length=93), nullable=False, comment='密码，密文'),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False, comment='管理员名称'),
    sa.Column('email', mysql.VARCHAR(length=30), nullable=True, comment='电子邮箱'),
    sa.Column('mobile', mysql.VARCHAR(length=20), nullable=True, comment='手机号'),
    sa.Column('group_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='管理员角色/组ID'),
    sa.Column('access_count', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='访问次数'),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='状态'),
    sa.Column('last_login', mysql.DATETIME(), nullable=True, comment='最后登录时间'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('administrator_id'),
    comment='管理员基本信息',
    mysql_comment='管理员基本信息',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('account', 'mis_administrator', ['account'], unique=True)
    op.create_table('news_comment_liking',
    sa.Column('liking_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('user_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('comment_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False, comment='评论ID'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否取消点赞, 0-未取消, 1-已取消'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('liking_id'),
    comment='评论点赞',
    mysql_comment='评论点赞',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_comment', 'news_comment_liking', ['user_id', 'comment_id'], unique=True)
    op.drop_table('user_article')
    # ### end Alembic commands ###
