"""empty message

Revision ID: dabcae436534
Revises: 0625454e3dcf
Create Date: 2020-07-01 07:50:04.433071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dabcae436534'
down_revision = '0625454e3dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_article', sa.Column('email', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_article', 'email')
    # ### end Alembic commands ###
