# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 09:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('nickname', models.CharField(blank=True, max_length=16, null=True, verbose_name='昵称')),
                ('username', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='用户名')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='昵称')),
                ('introduction', models.CharField(blank=True, max_length=120, null=True, verbose_name='昵称')),
                ('gender', models.BooleanField(choices=[(0, '男'), (1, '女')], default=0, max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('we_chat', models.CharField(blank=True, max_length=255, null=True)),
                ('qq', models.CharField(blank=True, max_length=12, null=True)),
                ('job', models.CharField(blank=True, max_length=12, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(choices=[(0, '未激活'), (1, '已激活')], default=0, max_length=1, verbose_name='激活标志')),
                ('dflag', models.BooleanField(choices=[(0, '删除'), (1, '正常')], default=1, max_length=1, verbose_name='删除标志')),
                ('status', models.BooleanField(choices=[(0, '禁用'), (1, '正常')], default=1, max_length=1, verbose_name='状态')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'tb_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('ctr_id', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=20, verbose_name='地址名称')),
                ('receiver', models.CharField(max_length=20, verbose_name='收货人')),
                ('place', models.CharField(max_length=50, verbose_name='地址')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机')),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='电子邮箱')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'db_table': 'tb_address',
                'ordering': ['-gmt_modified'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('author', models.CharField(blank=True, max_length=30, null=True)),
                ('source', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': '文章列表',
                'verbose_name_plural': '文章列表',
                'db_table': 'tb_article',
            },
        ),
        migrations.CreateModel(
            name='AttentionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.CharField(blank=True, max_length=30, null=True)),
                ('ctr_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '收藏客户',
                'verbose_name_plural': '收藏客户',
                'db_table': 'tb_attention_user',
            },
        ),
        migrations.CreateModel(
            name='CallOnDtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ctr_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户id')),
                ('customer', models.CharField(blank=True, max_length=30, null=True)),
                ('introduction', models.CharField(blank=True, max_length=120, null=True, verbose_name='昵称')),
                ('status', models.BooleanField(choices=[(0, '删除'), (1, '已跟进')], default=1, max_length=1, verbose_name='跟进状态')),
            ],
            options={
                'verbose_name': '用户规模',
                'verbose_name_plural': '用户规模',
                'db_table': 'tb_call_dtl',
            },
        ),
        migrations.CreateModel(
            name='CollectArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article_id', models.CharField(blank=True, max_length=30, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('is_top', models.BooleanField(default=0, max_length=1, verbose_name='是否置顶')),
            ],
            options={
                'verbose_name': '文章列表',
                'verbose_name_plural': '文章列表',
                'db_table': 'tb_collect_article',
            },
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.CharField(blank=True, max_length=16, null=True, verbose_name='昵称')),
                ('name', models.CharField(blank=True, max_length=12, null=True, verbose_name='用户名')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='昵称')),
                ('introduction', models.CharField(blank=True, max_length=120, null=True, verbose_name='昵称')),
                ('gender', models.BooleanField(choices=[(0, '男'), (1, '女')], default=0, max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('we_chat', models.CharField(blank=True, max_length=255, null=True)),
                ('qq', models.CharField(blank=True, max_length=12, null=True)),
                ('job', models.IntegerField(choices=[(0, 'IT｜互联网｜通信｜电子'), (1, '金融｜银行｜保险'), (2, '房产｜建筑建设｜物业'), (3, '广告｜传媒｜印刷出版'), (4, '消费零售｜贸易｜交通物流'), (5, '加工制造｜仪表设备'), (6, '管理咨询|教育科研｜中介服务'), (7, '医药生物｜医疗保健'), (8, '酒店旅游'), (9, '能源矿产｜石油化工'), (10, '政府｜非营利机构｜科研'), (11, '其他')], default=4, verbose_name='职业')),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('is_delete', models.BooleanField(choices=[(0, '删除'), (1, '正常')], default=1, max_length=1, verbose_name='删除标志')),
                ('status', models.BooleanField(choices=[(1, '潜在客户'), (2, '目标客户'), (3, '成交客户'), (4, '现实客户'), (5, '流失客户'), (6, '死亡客户')], default=1, max_length=1, verbose_name='状态')),
                ('star', models.IntegerField(choices=[(1, '一星级'), (2, '二星级'), (3, '三星级'), (4, '四星级'), (5, '五星级')], default=1, verbose_name='星级')),
                ('origin', models.IntegerField(choices=[(1, '老客户'), (2, '独立开发'), (3, '客户介绍'), (4, '客户介绍'), (5, '促销活动'), (6, '展览展会')], default=2, verbose_name='来源')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户id')),
                ('role', models.CharField(blank=True, max_length=16, null=True)),
                ('ctr_type', models.BooleanField(choices=[(0, '企业客户'), (1, '个人客户')], default=0, max_length=1, verbose_name='客户类型')),
                ('grade_id', models.IntegerField(blank=True, null=True, verbose_name='规模id')),
            ],
            options={
                'verbose_name': '客户表',
                'verbose_name_plural': '客户表',
                'db_table': 'tb_customer',
            },
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ctr_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户id')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('customer', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.IntegerField(choices=[(0, '删除'), (1, '已发送'), (2, '待发送'), (3, '草稿'), (4, '失败')], default=1, verbose_name='文章状态')),
                ('email_type', models.IntegerField(default=1, verbose_name='邮件类别')),
            ],
            options={
                'verbose_name': '用户规模',
                'verbose_name_plural': '用户规模',
                'db_table': 'tb_email_record',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户id')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.IntegerField(choices=[(0, '删除'), (1, '发布'), (2, '草稿')], default=1, verbose_name='文章状态')),
                ('is_top', models.BooleanField(default=0, max_length=1, verbose_name='是否置顶')),
                ('temp_type', models.IntegerField(blank=True, null=True, verbose_name='模板类别')),
            ],
            options={
                'verbose_name': '用户规模',
                'verbose_name_plural': '用户规模',
                'db_table': 'tb_email_temp',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_num', models.IntegerField(blank=True, null=True, verbose_name='开始')),
                ('end_num', models.IntegerField(blank=True, null=True, verbose_name='结束')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户id')),
                ('grade_type', models.IntegerField(choices=[(1, '系统'), (2, '自定义')], default=1, verbose_name='级别类型')),
            ],
            options={
                'verbose_name': '用户规模',
                'verbose_name_plural': '用户规模',
                'db_table': 'tb_grade',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('solar', models.DateField(verbose_name='阳历')),
                ('lunar', models.DateField(verbose_name='农历')),
                ('holi_type', models.IntegerField(choices=[(1, '系统'), (2, '自定义')], default=1, verbose_name='级别类型')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户规模',
                'verbose_name_plural': '用户规模',
                'db_table': 'tb_holiday',
            },
        ),
        migrations.CreateModel(
            name='SpaceArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户id')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.IntegerField(choices=[(0, '删除'), (1, '发布'), (2, '草稿')], default=1, verbose_name='文章状态')),
                ('is_top', models.BooleanField(default=0, max_length=1, verbose_name='是否置顶')),
            ],
            options={
                'verbose_name': '用户规模',
                'verbose_name_plural': '用户规模',
                'db_table': 'tb_space_article',
            },
        ),
        migrations.CreateModel(
            name='TaskDtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_type', models.IntegerField(choices=[(1, '单次任务'), (2, '重复任务')], default=1, verbose_name='任务类型')),
                ('ctr_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户id')),
                ('customer', models.CharField(blank=True, max_length=30, null=True)),
                ('introduction', models.CharField(blank=True, max_length=120, null=True, verbose_name='任务描述')),
                ('status', models.IntegerField(choices=[(1, '已完成'), (2, '已过期')], default=1, verbose_name='任务状态')),
            ],
            options={
                'verbose_name': '用户规模',
                'verbose_name_plural': '用户规模',
                'db_table': 'tb_task_dtl',
            },
        ),
    ]
